# archology_loader.R
# Hard-coded data preloader / validator for the archology taphonomy package
#
# What this does:
# - Loads a dataset (data.frame OR CSV/TSV file path)
# - Normalizes column names (trims tabs/extra spaces)
# - Validates required meta columns (types + constraints)
# - Treats skeletal element/count columns as integer counts (NA -> 0, with warning)
# - Emits aggregated warnings (or errors if strict=TRUE)
#
# No external schema file is used; the schema below is hard-coded based on meta.xlsx
#
# Author: generated by ChatGPT

#' Internal: trim tabs / repeated spaces in character vectors
.trim_ws <- function(x) {
  x <- gsub("[\t\r\n]+", " ", x)
  x <- gsub("[ ]{2,}", " ", x)
  trimws(x)
}

#' Internal: safe lower-case key for comparisons
.norm_key <- function(x) {
  x <- .trim_ws(as.character(x))
  tolower(x)
}

#' Hard-coded schema (meta + known skeletal columns example)
.archo_schema <- function() {
  # Meta columns (required)
  meta <- list(
    site_id           = list(type="integer", required=TRUE,  min=1),
    individual_id     = list(type="character", required=TRUE),
    site_name         = list(type="character", required=TRUE),
    layer_name        = list(type="character", required=FALSE, allow_na=TRUE),
    count_type        = list(type="logical",   required=TRUE),

    geological_period = list(type="categorical", required=TRUE,
                             allowed=c("Lower Pleistocene","Middle Pleistocene","Late Pleistocene","Holocene","NA")),
    cultural_period   = list(type="categorical", required=TRUE,
                             allowed=c("Lower Paleolithic","Middle Paleolithic","Upper Paleolithic","Mesolithic",
                                       "Neolithic","Chalcolithic","Bronze Age","Iron Age","Historical","NA")),
    culture_period_2  = list(type="character", required=FALSE, allow_na=TRUE),

    start_date_cal_bp = list(type="integer", required=FALSE, min=0, allow_na=TRUE),
    end_date_cal_bp   = list(type="integer", required=FALSE, min=0, allow_na=TRUE),

    mis_stage         = list(type="mis_stage", required=FALSE, allow_na=TRUE),

    karstic_system    = list(type="categorical", required=FALSE, allow_na=TRUE,
                             allowed=c("Cave","Rockshelter","NA")),
    karstic_system_2  = list(type="categorical", required=FALSE, allow_na=TRUE,
                             allowed=c("Cave Interior","Cave Entrance","Cave Vestibule","Rockshelter","NA")),
    open_air_site     = list(type="categorical", required=FALSE, allow_na=TRUE,
                             allowed=c("Open Air","NA")),
    open_air_site_2   = list(type="categorical", required=FALSE, allow_na=TRUE,
                             allowed=c("Fluvial deposits","Eolian deposits","Lake deposits","Enclosure ditches","NA")),

    region            = list(type="categorical", required=FALSE, allow_na=TRUE,
                             # Long list in meta.xlsx truncated; keep a permissive-but-guided list
                             allowed=c(
                               "Africa (Central)","Africa (East)","Africa (North)","Africa (South)","Africa (West)",
                               "Asia (Central)","Asia (East)","Asia (North)","Asia (South)","Asia (Southeast)","Asia (West)",
                               "Europe (Central)","Europe (East)","Europe (North)","Europe (South)","Europe (West)",
                               "North America","South America",
                               "Oceania (Australasia)","Oceania (Melanesia)","Oceania (Micronesia)","Oceania (Polynesia)",
                               "Caribbean","NA"
                             )),
    country           = list(type="character", required=FALSE, allow_na=TRUE),

    mni               = list(type="integer", required=FALSE, min=0, allow_na=TRUE),

    age_category      = list(type="categorical", required=FALSE, allow_na=TRUE,
                             allowed=c("Infantile","Juvenile","Subadult","Adult","Indet","NA")),
    n_infant          = list(type="integer", required=FALSE, min=0, allow_na=TRUE),
    n_juvenil         = list(type="integer", required=FALSE, min=0, allow_na=TRUE),
    n_subadult        = list(type="integer", required=FALSE, min=0, allow_na=TRUE),
    n_adult           = list(type="integer", required=FALSE, min=0, allow_na=TRUE),

    gender            = list(type="categorical", required=FALSE, allow_na=TRUE,
                             allowed=c("Female","Male","Indet/Mixed","NA")),

    taphonomic_context = list(type="categorical", required=FALSE, allow_na=TRUE,
                              allowed=c(
                                "Cannibalism","Carnivore den(transport)","Carnivore scavange (in situ)",
                                "Geological transport","Funerary Context","Unknown","NA"
                              )),
    funerary_context   = list(type="categorical", required=FALSE, allow_na=TRUE,
                              allowed=c(
                                "Inhumantion single","Inhumation multiple","No inhumation","Collective burial","NA"
                              )),
    discovery_context  = list(type="categorical", required=FALSE, allow_na=TRUE,
                              allowed=c("Quarry","Formal excavation","Casual","NA")),
    degree_of_excavation = list(type="categorical", required=FALSE, allow_na=TRUE,
                                allowed=c("Complete","Partial","Indet","NA")),
    hominin_species    = list(type="categorical", required=FALSE, allow_na=TRUE,
                              # Meta.xlsx shows truncated examples; keep common ones + NA
                              allowed=c("H. sapiens","H. neanderthalensis","H. heidelbergensis","H. erectus",
                                        "H. antecessor","H. naledi","H. floresiensis","Hominin indet","NA")),
    observation        = list(type="character", required=FALSE, allow_na=TRUE),
    reference          = list(type="character", required=FALSE, allow_na=TRUE)
  )

  # Known skeletal columns from the uploaded meta.xlsx (you said more exist, but constraints are identical)
  skeletal_known <- c(
    "Cranium",
    "Neurocranium bone",
    "Neurocranium bone indet",
    "Frontal bone",
    "Parietal bone",
    "Parietal bone indet",
    "Parietal bone Right",
    "Parietal bone Left"
  )

  list(meta=meta, skeletal_known=skeletal_known)
}

#' Internal: coerce "TRUE/FALSE", 0/1, yes/no into logical
.as_logical_safe <- function(x) {
  if (is.logical(x)) return(x)
  if (is.numeric(x)) return(!is.na(x) & x != 0)
  if (is.character(x) || is.factor(x)) {
    y <- .norm_key(x)
    out <- rep(NA, length(y))
    out[y %in% c("true","t","1","yes","y")]  <- TRUE
    out[y %in% c("false","f","0","no","n")] <- FALSE
    return(out)
  }
  rep(NA, length(x))
}

#' Internal: integer coercion with warnings
.as_integer_safe <- function(x) {
  if (is.integer(x)) return(x)
  if (is.logical(x)) return(as.integer(x))
  if (is.factor(x)) x <- as.character(x)
  suppressWarnings(ix <- as.integer(x))
  ix
}

#' Internal: detect values that look like non-integers
.has_noninteger_numeric <- function(x) {
  if (!is.numeric(x)) return(FALSE)
  any(!is.na(x) & abs(x - round(x)) > 1e-9)
}

#' Internal: validate MIS stage (e.g. "3a", "5e", "1") or NA
.is_valid_mis <- function(x) {
  if (is.na(x) || .norm_key(x) == "na") return(TRUE)
  grepl("^[0-9]{1,2}([a-e])?$", .norm_key(x))
}

#' Internal: categorical matching (case-insensitive), with optional "NA" string
.match_allowed <- function(val, allowed) {
  if (is.na(val)) return(TRUE)
  vk <- .norm_key(val)
  if (vk == "na") return(TRUE)
  ak <- .norm_key(allowed)
  vk %in% ak
}

#' Internal: determine "max per body" for some bones (for optional MNI upper-limit warnings)
.max_per_body_for_bone <- function(colname) {
  cn <- .trim_ws(colname)
  if (grepl("Right$|Left$", cn)) return(1L)
  if (cn == "Cranium") return(1L)
  if (cn == "Frontal bone") return(1L)
  if (cn == "Parietal bone") return(2L)
  # fallback: unknown; don't enforce
  NA_integer_
}

#' Load + validate an archology taphonomy dataset
#'
#' @param x data.frame/tibble OR a file path (.csv/.tsv/.txt)
#' @param strict logical; if TRUE, schema violations become errors (stop())
#' @param na_to_zero_skeletal logical; if TRUE, skeletal NAs are converted to 0 (with warning)
#' @param guess_skeletal logical; if TRUE, any non-meta numeric column is treated as skeletal count
#' @return validated data.frame with attribute "validation_report"
#'
#' @export
archo_preload <- function(x,
                          strict = FALSE,
                          na_to_zero_skeletal = TRUE,
                          guess_skeletal = TRUE) {

  # --- load ---
  if (is.character(x) && length(x) == 1L) {
    fp <- x
    if (!file.exists(fp)) stop("File does not exist: ", fp, call.=FALSE)

    ext <- tolower(tools::file_ext(fp))
    if (ext %in% c("csv")) {
      df <- utils::read.csv(fp, stringsAsFactors = FALSE, check.names = FALSE)
    } else if (ext %in% c("tsv","txt")) {
      df <- utils::read.delim(fp, stringsAsFactors = FALSE, check.names = FALSE)
    } else {
      stop("Unsupported file extension: .", ext, " (supported: csv, tsv, txt).", call.=FALSE)
    }
  } else if (is.data.frame(x)) {
    df <- x
  } else {
    stop("x must be a data.frame or a file path to CSV/TSV.", call.=FALSE)
  }

  report <- list(
    renamed_columns = character(),
    missing_required = character(),
    type_coercions = character(),
    invalid_values = character(),
    constraint_violations = character(),
    skeletal_na_to_zero = character(),
    skeletal_negative = character(),
    skeletal_noninteger = character(),
    unknown_columns = character()
  )

  # --- normalize column names (trim whitespace/tabs) ---
  original_names <- names(df)
  clean_names <- .trim_ws(original_names)

  if (!identical(original_names, clean_names)) {
    report$renamed_columns <- paste0("Renamed columns: ",
                                    paste0(sprintf("'%s' -> '%s'", original_names, clean_names), collapse=", "))
    names(df) <- clean_names
  }

  schema <- .archo_schema()
  meta_spec <- schema$meta

  # --- required columns ---
  required_cols <- names(Filter(function(s) isTRUE(s$required), meta_spec))
  missing <- setdiff(required_cols, names(df))
  if (length(missing) > 0) {
    report$missing_required <- paste0("Missing required columns: ", paste(missing, collapse=", "))
    if (strict) stop(report$missing_required, call.=FALSE)
  }

  # --- validate / coerce meta columns ---
  for (col in intersect(names(meta_spec), names(df))) {
    spec <- meta_spec[[col]]
    val <- df[[col]]

    # Allow NA?
    allow_na <- isTRUE(spec$allow_na)

    if (spec$type == "integer") {
      if (.has_noninteger_numeric(val)) {
        report$type_coercions <- c(report$type_coercions,
                                  sprintf("Column '%s' contains non-integer numeric values; coerced to integer (truncation).", col))
      }
      coerced <- .as_integer_safe(val)
      # Warn if coercion introduced NA where original had non-NA
      if (any(!is.na(val) & is.na(coerced))) {
        report$type_coercions <- c(report$type_coercions,
                                  sprintf("Column '%s' had values that could not be converted to integer (set to NA).", col))
      }
      df[[col]] <- coerced

      if (!is.null(spec$min)) {
        bad <- which(!is.na(df[[col]]) & df[[col]] < spec$min)
        if (length(bad) > 0) {
          report$constraint_violations <- c(report$constraint_violations,
                                           sprintf("Column '%s' has %d value(s) below %s (min).", col, length(bad), spec$min))
        }
      }

    } else if (spec$type == "logical") {
      coerced <- .as_logical_safe(val)
      if (any(!is.na(val) & is.na(coerced))) {
        report$type_coercions <- c(report$type_coercions,
                                  sprintf("Column '%s' had values that could not be converted to logical (set to NA).", col))
      }
      df[[col]] <- coerced

    } else if (spec$type == "character") {
      if (is.factor(val)) val <- as.character(val)
      df[[col]] <- .trim_ws(val)

    } else if (spec$type == "categorical") {
      if (is.factor(val)) val <- as.character(val)
      val <- .trim_ws(val)
      df[[col]] <- val

      allowed <- spec$allowed
      if (!is.null(allowed)) {
        bad_idx <- which(!vapply(val, .match_allowed, logical(1), allowed=allowed))
        if (length(bad_idx) > 0) {
          examples <- unique(val[bad_idx])[1:min(5, length(unique(val[bad_idx])))]
          report$invalid_values <- c(report$invalid_values,
                                     sprintf("Column '%s' has %d invalid categorical value(s). Examples: %s",
                                             col, length(bad_idx), paste0(sprintf("'%s'", examples), collapse=", ")))
        }
      }

    } else if (spec$type == "mis_stage") {
      if (is.factor(val)) val <- as.character(val)
      val <- .trim_ws(val)
      df[[col]] <- val
      bad_idx <- which(!vapply(val, .is_valid_mis, logical(1)))
      if (length(bad_idx) > 0) {
        examples <- unique(val[bad_idx])[1:min(5, length(unique(val[bad_idx])))]
        report$invalid_values <- c(report$invalid_values,
                                   sprintf("Column '%s' has %d invalid MIS stage value(s). Examples: %s",
                                           col, length(bad_idx), paste0(sprintf("'%s'", examples), collapse=", ")))
      }
    }
  }

  # --- cross-field constraints ---
  if (all(c("start_date_cal_bp","end_date_cal_bp") %in% names(df))) {
    s <- df$start_date_cal_bp
    e <- df$end_date_cal_bp
    bad <- which(!is.na(s) & !is.na(e) & s < e)
    if (length(bad) > 0) {
      report$constraint_violations <- c(report$constraint_violations,
                                       sprintf("Found %d row(s) where start_date_cal_bp < end_date_cal_bp (expected start >= end).", length(bad)))
    }
  }

  if (all(c("karstic_system","open_air_site") %in% names(df))) {
    k <- df$karstic_system
    o <- df$open_air_site
    both <- which(!is.na(k) & .norm_key(k) != "na" & !is.na(o) & .norm_key(o) != "na")
    if (length(both) > 0) {
      report$constraint_violations <- c(report$constraint_violations,
                                       sprintf("Found %d row(s) where BOTH karstic_system and open_air_site are set (expected only one).", length(both)))
    }
  }

  # --- infer skeletal columns ---
  meta_cols_present <- intersect(names(meta_spec), names(df))
  candidate_cols <- setdiff(names(df), meta_cols_present)

  skeletal_cols <- character()

  # Known skeletal columns explicitly
  skeletal_cols <- intersect(schema$skeletal_known, names(df))

  # Guess additional skeletal columns: any candidate numeric/integer column
  if (guess_skeletal) {
    extra_numeric <- candidate_cols[vapply(df[candidate_cols], function(z) is.numeric(z) || is.integer(z), logical(1))]
    skeletal_cols <- unique(c(skeletal_cols, extra_numeric))
  }

  # Unknown columns (not meta, not skeletal-typed)
  unknown <- setdiff(candidate_cols, skeletal_cols)
  if (length(unknown) > 0) {
    report$unknown_columns <- paste0("Unknown (non-meta) column(s) detected (kept as-is): ", paste(unknown, collapse=", "))
  }

  # --- validate skeletal columns ---
  if (length(skeletal_cols) > 0) {
    for (col in skeletal_cols) {
      v <- df[[col]]

      # Coerce to integer (counts)
      if (.has_noninteger_numeric(v)) {
        report$skeletal_noninteger <- c(report$skeletal_noninteger,
                                       sprintf("Skeletal column '%s' had non-integer numeric values; coerced to integer.", col))
      }

      coerced <- .as_integer_safe(v)

      # NA -> 0 (counts)
      if (na_to_zero_skeletal && any(is.na(coerced))) {
        n_na <- sum(is.na(coerced))
        report$skeletal_na_to_zero <- c(report$skeletal_na_to_zero,
                                       sprintf("Skeletal column '%s' had %d NA value(s); replaced with 0 (NA treated as 'not identified').", col, n_na))
        coerced[is.na(coerced)] <- 0L
      }

      # Negative check
      neg <- which(!is.na(coerced) & coerced < 0)
      if (length(neg) > 0) {
        report$skeletal_negative <- c(report$skeletal_negative,
                                     sprintf("Skeletal column '%s' has %d negative value(s) (counts must be >= 0).", col, length(neg)))
      }

      df[[col]] <- coerced
    }

    # Optional upper limit checks using MNI (when available)
    if ("mni" %in% names(df)) {
      mni <- df$mni
      for (col in skeletal_cols) {
        mpb <- .max_per_body_for_bone(col)
        if (!is.na(mpb)) {
          bad <- which(!is.na(mni) & mni > 0 & df[[col]] > (mni * mpb))
          if (length(bad) > 0) {
            report$constraint_violations <- c(report$constraint_violations,
                                             sprintf("Skeletal column '%s' exceeds MNI-based max (%d per body) in %d row(s).", col, mpb, length(bad)))
          }
        }
      }
    }
  }

  # --- uniqueness-ish checks (soft warnings) ---
  if (all(c("site_id","site_name") %in% names(df))) {
    # If the same site_id maps to multiple site_name values, warn
    tmp <- stats::aggregate(df$site_name, by=list(site_id=df$site_id), FUN=function(z) length(unique(z[!is.na(z)])))
    bad <- tmp$site_id[!is.na(tmp$x) & tmp$x > 1]
    if (length(bad) > 0) {
      report$constraint_violations <- c(report$constraint_violations,
                                       sprintf("site_id maps to multiple site_name values for %d site_id(s). Example site_id(s): %s",
                                               length(bad), paste(head(bad, 5), collapse=", ")))
    }
  }

  # --- finalize warnings/errors ---
  # Flatten report to messages
  messages <- unlist(report, use.names = FALSE)
  messages <- messages[!is.na(messages) & nzchar(messages)]

  attr(df, "validation_report") <- report

  if (length(messages) > 0) {
    msg <- paste0(
      "archo_preload validation report:\n",
      paste0("- ", messages, collapse="\n")
    )
    if (strict) stop(msg, call.=FALSE)
    warning(msg, call.=FALSE)
  }

  df
}

#' Convenience: print report in a friendly way
#' @export
archo_print_report <- function(x) {
  rep <- attr(x, "validation_report")
  if (is.null(rep)) {
    cat("No validation_report attribute found.\n")
    return(invisible(NULL))
  }
  messages <- unlist(rep, use.names = FALSE)
  messages <- messages[!is.na(messages) & nzchar(messages)]
  if (length(messages) == 0) {
    cat("No issues detected.\n")
  } else {
    cat("Validation issues:\n")
    cat(paste0("- ", messages, collapse="\n"), "\n")
  }
  invisible(rep)
}
